<?xml version="1.0"?>
<robot name="feldschwarm_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="wheel_lenght" value="0.1"/>
    <xacro:property name="wheel_width" value="0.025" />
    <xacro:property name="wheel_radius" value="0.2"/>
    <xacro:property name="chasiss_height" value="0.4"/>
    <xacro:property name="chasiss_width" value="1"/>
    <xacro:property name="chasiss_length" value="1.5"/>
    <xacro:include filename="$(find test_package)/urdf/wheel.urdf.xacro" />
    <!--xacro:include filename="$(find test_package)/urdf/leg.urdf.xacro" /-->
    <!--xacro:include filename="$(find test_package)/urdf/vlp16_mount.urdf.xacro" /-->


    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="wheelbase" value="1.4" />
    <xacro:property name="track" value="1" />
    <xacro:property name="wheel_vertical_offset" value="0" />
    <xacro:property name="PI" value="3.1415926535897931" />



    <xacro:property name="base_vertical_offset" value="${wheel_radius-wheel_vertical_offset}" />

    <link name="base_footprint"/>

    <joint name="footprint_joint" type="fixed">
       <origin xyz="0 0 ${base_vertical_offset}" rpy="0 0 0" />
       <parent link="base_footprint" />
       <child link="robot_chasiss" />
    </joint>






    <link name="robot_chasiss">
      <visual>
        <geometry>
          <box size="${chasiss_length} ${chasiss_width} ${chasiss_height}"/>
        </geometry>
      </visual>

      <collision>
        <geometry>
          <box size="${chasiss_length} ${chasiss_width} ${chasiss_height}"/>
        </geometry> 
      </collision>

      <inertial>
        <mass value="1"/>
        <inertia ixx="0.166667" ixy="0" ixz="0" iyy="0.166667" iyz="0" izz="0.166667"/>
      </inertial>




    </link>


    
    <link name="lidar_stand">
      <visual>
        <geometry>
          <box size="0.1 0.1 0.2" />
        </geometry>
        <!--material name="black" /-->
      </visual>
      <collision>
        <geometry>
          <box size="0.1 0.1 0.2" />
        </geometry>

        
      </collision>
      <inertial>
        <mass value="1" />
        <inertia ixx="0.145833" ixy="0.0" ixz="0.145833" iyy="0.0" iyz="0.0" izz="0.1250"/>
      </inertial>
        
      
        
      
    </link>
    
    <joint name="joint_name" type="fixed">
      <parent link="robot_chasiss"/>
      <child link="lidar_stand"/>
      <axis xyz="0.0 0.0 1.0"/>
      <origin xyz="0.0 0.0 0.3"/>
      <!--limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/-->
    </joint>

   


    

    <xacro:feldschwarm_wheel wheel_prefix="front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:feldschwarm_wheel>
    <xacro:feldschwarm_wheel wheel_prefix="front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:feldschwarm_wheel>
    <xacro:feldschwarm_wheel wheel_prefix="rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:feldschwarm_wheel>
    <xacro:feldschwarm_wheel wheel_prefix="rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:feldschwarm_wheel>



    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
    <VLP-16 parent="robot_chasiss" name="velodyne" topic="/velodyne_points" hz="10" samples="1024" gpu="false" lasers="16" max_range="100">
      <origin xyz="0 0 0.4" rpy="0 0 0" />
    </VLP-16>


    
    

    
























    
</robot>
